"""add phone number

Revision ID: a5b03902b51d
Revises: 83e0a8f903be
Create Date: 2021-12-08 19:36:02.799209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a5b03902b51d"
down_revision = "83e0a8f903be"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("phone_number", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "phone_number")
    # ### end Alembic commands ###
